### ISSUE TITLE
TLS not working with openJDK8

### ISSUE THREAD

**Issue by uweschaefer** [yidongnan/grpc-spring-boot-starter#139]
Not sure, if this is the right forum, but i failed to use TLS.

When connecting, i get 

```
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:629) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[netty-tcnative-boringssl-static-2.0.20.Final.jar:2.0.20.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:488) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1036) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1144) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:211) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) ~[netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187) ~[na:1.8.0_181]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:258) ~[na:1.8.0_181]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[na:1.8.0_181]
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:237) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:625) ~[netty-handler-4.1.29.Final.jar:4.1.29.Final]
	... 26 common frames omitted
```

Looking at ProtocolVersion (in openJDK8) indeed reveals:

```
    private static ProtocolVersion valueOf(int var0) {
        if (var0 == SSL30.v) {
            return SSL30;
        } else if (var0 == TLS10.v) {
            return TLS10;
        } else if (var0 == TLS11.v) {
            return TLS11;
        } else if (var0 == TLS12.v) {
            return TLS12;
        } else if (var0 == SSL20Hello.v) {
            return SSL20Hello;
        } else {
            int var1 = var0 >>> 8 & 255;
            int var2 = var0 & 255;
            return new ProtocolVersion(var0, "Unknown-" + var1 + "." + var2);
        }
    }
```

Is there a way to use TLS1.2?

Setup:

Server and Client run on openjdk8. I am using boringssl-static on both sides
```
   <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.20.Final</version>
    </dependency>
```

Client properties:

```
grpc.client.x.port=9443
grpc.client.x.host=localhost
grpc.client.x.security.trustCertCollectionPath=src/etc/certificates/trusted-servers/localhost.crt
grpc.client.x.security.authorityOverride=localhost
```

Server properties:
```
grpc.server.port=9443
grpc.server.security.enabled=true
grpc.server.security.certificateChainPath=src/etc/certificates/localhost.crt
grpc.server.security.privateKeyPath=src/etc/certificates/localhost.key
```

**Comment by uweschaefer** [comment]
maybe a related discussion
http://openjdk.5641.n7.nabble.com/sun-security-ssl-ProtocolVersion-valueOf-in-Java8-and-TLSv1-3-td350186.html

**Comment by uweschaefer** [comment]
same with oracle 1.8.0_191

```
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187) ~[na:1.8.0_191]
```

**Comment by ST-DDT** [comment]
AFAICT it is possible to configure netty as roughly explained on [SO](https://stackoverflow.com/a/42668378/4573065).

Please try to overwrite your `NettyServerFactory` bean's `configureSecurity` method as follows

````java
@Override
    protected void configureSecurity(final NettyServerBuilder builder) {
        final Security security = this.properties.getSecurity();
        if (security.isEnabled()) {
            final File certificateChainFile = toCheckedFile("certificateChain", security.getCertificateChainPath());
            final File privateKeyFile = toCheckedFile("privateKey", security.getPrivateKeyPath());
            final SslContextBuilder sslContextBuilder = GrpcSslContexts.forServer(certificateChainFile, privateKeyFile);

            if (security.getClientAuth() != ClientAuth.NONE) {
                sslContextBuilder.clientAuth(security.getClientAuth());

                final String trustCertCollectionPath = security.getTrustCertCollectionPath();
                if (trustCertCollectionPath != null && !trustCertCollectionPath.isEmpty()) {
                    final File trustCertCollectionFile = toCheckedFile("trustCertCollection", trustCertCollectionPath);
                    sslContextBuilder.trustManager(trustCertCollectionFile);
                }
            }
            sslContextBuilder.protocols("TLSv1.2"); // I'm not sure with the name of the protocol

            try {
                builder.sslContext(sslContextBuilder.build());
            } catch (final SSLException e) {
                throw new IllegalStateException("Failed to create ssl context for grpc server", e);
            }
        }
    }
````

and report whether this worked as expected.

**Comment by uweschaefer** [comment]
nope, does not work. if i pass a nonsense parameter to sslContextBuilder.protocols i see it in the logs (so i know the code is actually used), 

```
Caused by: java.lang.IllegalArgumentException: Protocol TLSvNonsense is not supported.
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols(ReferenceCountedOpenSslEngine.java:1424)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:272)
```

but passing TLSv1.2 still makes the client complain
```
Caused by: java.lang.IllegalArgumentException: TLSv1.3
	at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187) ~[na:1.8.0_181]
```

**Comment by uweschaefer** [comment]
tried to set the protocol on the engine directly via:
````
                        SslContext ctx = new DelegatingSslContext(sslContextBuilder.build()) {
                            @Override
                            protected void initEngine(SSLEngine engine) {
                                engine.setEnabledProtocols(new String[]{"TLSv1.2", "SSLv2Hello"});
                            }
                        };
```

without any luck.

**Comment by ST-DDT** [comment]
Maybe you have to configure the client instead? Works similar to the server impl.

**Comment by ST-DDT** [comment]
I'm not sure but maybe this has been reported to and fixed by netty already: https://github.com/netty/netty/issues/8458
Try using netty `4.1.31.Final`

**Comment by uweschaefer** [comment]
no luck configuring ACF

**Comment by uweschaefer** [comment]
wait-a-minute... dunno if i screwed up my run configs, but i cannot reproduce it after cleaning up. gimme a minute...

**Comment by ST-DDT** [comment]
I created an issue upstream (https://github.com/grpc/grpc-java/issues/5080), to let them fix it. The next grpc release is going to released soon. If they include it in there we can just update to the latest grpc version. If they don't include it we should add it to our Readme's Troubleshooting section.

**Comment by uweschaefer** [comment]
It is weird.

what works for me is, on the server side, add
```
  <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>4.1.31.Final</version>
    </dependency>
```

and on the client side
```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>4.1.31.Final</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler
      </artifactId>
      <version>4.1.31.Final</version>
    </dependency>
```

i admit, i have no idea, why i need to explicitly include netty-handler, but this is the **one** way i got it to work, here.

**Comment by uweschaefer** [comment]
no tweaking of beans, with the above...

**Comment by uweschaefer** [comment]
thanks again @ST-DDT ! shall we close this issue or keep it for reference/reminder?

**Comment by ST-DDT** [comment]
Lets keep it open for now.
1.17 will be released in early december.
Then we will now whether we can update grpc or have to add a hint to the readme.

**Comment by uweschaefer** [comment]
Ah, i see. I was using 0.16.1 all the time, but the culprit is tcnative-boringssl. It looks like you need netty 4.1.13 for the 2.0.20 version to work with java8.
using 2.0.17 solved the thing again.

I am wondering, if we should advice users to use grpc-netty-shaded (in order to reduce the likability of issues from there and tcnative-boringssl version accoring to the [version sheet](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty) to get this to work without the hassle?
