### ISSUE TITLE
Cf support???

### ISSUE THREAD

**Issue by rocks4530** [yidongnan/grpc-spring-boot-starter#206]
Port binding is still an issue on CF. Only option is to use TCP port on CF. Any other options pliz ????

**Comment by ST-DDT** [comment]
What is CF referring to? Cloud Foundry?
What do you need for CF support? AFAICT grpc relies on HTTP/2 which always uses TCP or am I missing something?

**Comment by rocks4530** [comment]
Yes cloud foundry!! Many cf installation by default dosnt have TCP port support. We need to explicitly add this. The default router that CF uses  - gorouter doesn’t seem to support Http2. 

https://github.com/cloudfoundry/gorouter/issues/195

**Comment by ST-DDT** [comment]
Which side causes your issues? Client, Server or both?

Sorry, I know too little about CF and their connection management. 
This library solely relies on grpc-java/netty to establish the connections, so it might be useful to ask them for help. Could you open an issue in grpc-java / SO and link it here?
Maybe they can provide a hint to help me discover what is needed for CF support.

**Comment by ST-DDT** [comment]
Linking to https://github.com/LogNet/grpc-spring-boot-starter/issues/116 to share the solutions if any where found

**Comment by rocks4530** [comment]
The problem is with the connection. When a client connects to server by passing a message, it goes via gorouer (HTTP1.1) . There it throws exception. I am trying with some proxy(envoy/istio))

**Comment by ST-DDT** [comment]
Could you post the stacktrace here?
Which negotiationType do you use on the client side?

**Comment by rocks4530** [comment]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.grpc.StatusRuntimeException: UNAVAILABLE: io exception] with root cause
   2019-03-31T16:18:05.00+0530 [APP/PROC/WEB/0] OUT io.grpc.netty.shaded.io.netty.channel.ConnectTimeoutException: connection timed out: serverXXXXXXXXXXXXXXXX.com/X.X.X.X:12717
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00 [APP/PROC/WEB/0] OUT 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.19.0.jar!/:1.19.0]
   2019-03-31T16:18:05.00+0530 [APP/PROC/WEB/0] OUT 	at java.base/java.lang.Thread.run(Unknown S

**Comment by ST-DDT** [comment]
All I can tell from the stacktrace is that the target ip/port is wrong or the target is not running.
AFAICT there is nothing I can do about that.

Have you contacted the grpc-java- or CF-team about this issue yet?

**Comment by rocks4530** [comment]
It seems we need to set up a network policy or open a TCP port in CF. By default, this set up is not there. 
Currently i am using https://github.com/grpc-ecosystem/grpc-gateway. Thanks for all support.
