### ISSUE TITLE
GRPC-Context-scoped beans

### ISSUE THREAD

**Issue by ByJacob** [yidongnan/grpc-spring-boot-starter#211]
Hi

My propose is create GrpcContextHolder, simmilar to org.springframework.web.context.request.RequestContextHolder

**Comment by ST-DDT** [comment]
I assume you refer to `io.grpc.Context`.
What would be the benefits of using a `GrpcContextHolder` over `Context.current()`?

**Comment by ByJacob** [comment]
Ok my propos is stupid xD. I write it too fast. I am sorry. 

I poropose it because i looking solution how  use beans with annotatnion @RequestScope in grpc Services. Meaby add grpc scope in starter??

**Comment by ST-DDT** [comment]
I'll have a in-depth look at that in a few days, but sounds like an interesting idea.

https://www.baeldung.com/spring-custom-scope
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/config/Scope.html
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-factory-scopes-custom

**Comment by ST-DDT** [comment]
IMO it should be possible to add a grpc-request scope.
But this library currently does not handle sessions and Im not sure whether grpc actually has a notion a session. 
Are there any other grpc scopes that you are aware of/youmight need?

**Comment by ByJacob** [comment]
In now i don't need more. Spring mvc use class ThreadLocal for save objects/beans in scope (org.springframework.web.context.request.AbstractRequestAttributesScope and org.springframework.web.context.request.RequestContextHolder)

**Comment by ST-DDT** [comment]
**WARNING:** Do **NOT** use thread locals with grpc.
Each message/interceptor call might be executed by a different thread and threads might be reused by different messages/calls.
That's what `Context`s are for.

**Comment by ST-DDT** [comment]
Mhh, if I match the scope to the context I get some weird results. Maybe I should bind it to the server call only. This requires some more thoughts, so I will move it to the next release v2.5.0. Unless there's an objection.

**Comment by ST-DDT** [comment]
PR #259 adds a grpcRequest based scope. So you have a singe scope (and thus beans) for all incoming messages of the same request, but different requests will have different beans.

Binding it to grpc's `Context`s is not useful because the scope would mostly start just in the service implementation and thus different messages in the same request would potentially start a new scope and thus receive new beans.

**Comment by ST-DDT** [comment]
Added via #259

**Comment by ST-DDT** [comment]
Afaict there is nothing related to Threads in the implementation, so it should work with reactor just fine.

Could you give me the error message you are getting?

**Comment by mahdibohloul** [comment]
Thank you for your reply.

I have a `WorkContext` service where I put the current user or the current language and something like that which is associated with a request.

```Kotlin
interface WorkingContext {
  fun setUserId(userId: String)
  fun getUserId(): String
}
```
And in the implementation:

```Kotlin
@Service
@Scope(scopeName = GrpcRequestScope.GRPC_REQUEST_SCOPE_NAME, proxyMode = ScopedProxyMode.TARGET_CLASS)
class WorkingContextImp(
  @Autowired val logger: Logger
) : WorkingContext {
  @PostConstruct
  fun init() {
    logger.info("Working context created")
  }
  private var userId: String = ""
  
  override fun getUserId(): String {
    return this.userId
  }

  override fun setUserId(userId: String) {
    this.userId = userId
  }
}
```

Now in a server interceptor with the lowest precedence, I'm doing something like that:
```Kotlin

@Order(Ordered.LOWEST_PRECEDENCE)
class WorkingContextInterceptor(
  @Autowired val logger: Logger,
  @Autowired val workingContext: WorkingContext
) : ServerInterceptor {
  override fun <ReqT : Any?, RespT : Any?> interceptCall(
    call: ServerCall<ReqT, RespT>?,
    headers: Metadata?,
    next: ServerCallHandler<ReqT, RespT>?
  ): ServerCall.Listener<ReqT> {
    workingContext.setUserId( /*get user id from the headers*/ )
    return Contexts.interceptCall(Context.current(), call, headers, next)
  }
}

```

Now I have two services as below:

Service B:
```Kotlin
@Service
class ServiceB(
  @Autowired val workingContext: WorkingContext,
) {
  fun getUserId() = workingContext.getUserId.toMono()
}
```

Service A:
```Kotlin
@Service
class ServiceA(
  @Autowired val workingContext: WorkingContext,
  @Autowired val logger: Logger,
  @Autowired val serviceB: ServiceB
) {
  fun test(): Mono<String> {
    return Mono.fromCallable { workingContext.getUserId() }
    .doOnNext { logger.info("The user id in service A is: $it") }
    .flatMap { serviceB.getUserId() } 
    .doOnNext { logger.info("The user id in inner service B is: $it") }
  }
}
```

And it works fine and the user id print well and everything is right!
But if I change ServiceA implementation as below:

```Kotlin
@Service
class ServiceA(
  @Autowired val workingContext: WorkingContext,
  @Autowired val logger: Logger,
  @Autowired val serviceB: ServiceB
) {
  fun test(): Mono<String> {
    return Mono.fromCallable { workingContext.getUserId() }
    .doOnNext { logger.info("The user id in service A is: $it") }
    .publishOn(Schedulers.boundedElastic()) //This line has been added
    .flatMap { serviceB.getUserId() } 
    .doOnNext { logger.info("The user id in inner service B is: $it") }
  }
}
```
This test will fail with the following error:
```
20:24:09.359 [grpc-default-executor-0] INFO  cab.tapsi.scheduleddelivery.infrastructure.context.services.WorkingContextImp - Working context created
20:24:09.382 [grpc-default-executor-0] INFO  cab.tapsi.scheduleddelivery.grpc.ScheduledDeliveryGrpc - The user id in service A is: 1
20:24:09.397 [boundedElastic-1] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.workingContextImp': Scope 'grpcRequest' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Trying to access grpcRequest-Scope, but it was not started for this thread.
Caused by: org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.workingContextImp': Scope 'grpcRequest' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Trying to access grpcRequest-Scope, but it was not started for this thread.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:383) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:676) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.scheduleddelivery.infrastructure.context.services.WorkingContextImp$$EnhancerBySpringCGLIB$$26bbe10b.getUserId(<generated>) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler.getUserId(OrderGrpcHandler.kt:94) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler$$FastClassBySpringCGLIB$$8aba75bf.invoke(<generated>) ~[main/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.libs.kafka.kafkaproducerstarter.annotation.AnnotationAwareKafkaStreamOperationsInterceptor.invoke(AnnotationAwareKafkaStreamOperationsInterceptor.java:54) ~[kafka-producer-starter-2.0.1.jar:2.0.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler$$EnhancerBySpringCGLIB$$824abf50.getUserId(<generated>) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.ScheduledDeliveryGrpc.runMatching$lambda-48(ScheduledDeliveryGrpc.kt:757) ~[main/:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) [reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) [reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.4.13.jar:3.4.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: Trying to access grpcRequest-Scope, but it was not started for this thread.
	at cab.tapsi.scheduleddelivery.infrastructure.grpc.scope.GrpcRequestScope.getCurrentScopeContainer(GrpcRequestScope.kt:55) ~[main/:?]
	at cab.tapsi.scheduleddelivery.infrastructure.grpc.scope.GrpcRequestScope.get(GrpcRequestScope.kt:23) ~[main/:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:676) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.scheduleddelivery.infrastructure.context.services.WorkingContextImp$$EnhancerBySpringCGLIB$$26bbe10b.getUserId(<generated>) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler.getUserId(OrderGrpcHandler.kt:94) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler$$FastClassBySpringCGLIB$$8aba75bf.invoke(<generated>) ~[main/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.libs.kafka.kafkaproducerstarter.annotation.AnnotationAwareKafkaStreamOperationsInterceptor.invoke(AnnotationAwareKafkaStreamOperationsInterceptor.java:54) ~[kafka-producer-starter-2.0.1.jar:2.0.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.14.jar:5.3.14]
	at cab.tapsi.scheduleddelivery.grpc.handlers.OrderGrpcHandler$$EnhancerBySpringCGLIB$$824abf50.getUserId(<generated>) ~[main/:?]
	at cab.tapsi.scheduleddelivery.grpc.ScheduledDeliveryGrpc.runMatching$lambda-48(ScheduledDeliveryGrpc.kt:757) ~[main/:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.13.jar:3.4.13]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.13.jar:3.4.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

```

**Comment by ST-DDT** [comment]
The error message is a bit confusing here.
The issue isn't really the Thread, but the (missing) GrpcContext.
I assume the `Schedulers.boundedElastic()` isn't a grpc specific utility thus, it doesn't preserve the GrpcContext when starting new execution contexts.

If you try to access `GrpcContext.current()` after calling the `publishOn`, you will either get an error or an empty context (AFAICT).

Sadly I'm not familiar with reactor grpc to point you to the correct utility. You might want to consult the reactor docs for more information. If you find a solution please report it back to me, so I can add it to our documentation.

**Comment by ST-DDT** [comment]
I tried to improve the error message a bit, is that a bit clearer?
https://github.com/yidongnan/grpc-spring-boot-starter/pull/777

**Comment by mahdibohloul** [comment]
I think it's because of this line in the `GrpcRequextScoe` file:
```Java
ScopedBeansContainer scopedBeansContainer = GRPC_REQUEST_KEY.get();
```
In the underlying of this functionality, it's going to access the thread-local of the current thread to find the current context, and then find the key.

According to the project reactor [documentation](https://projectreactor.io/docs/core/release/reference/#context):

> One of the big technical challenges encountered when switching from an imperative programming perspective to a reactive programming mindset lies in how you deal with threading.
> Contrary to what you might be used to, in reactive programming, you can use a Thread to process several asynchronous sequences that run at roughly the same time (actually, in non-blocking locksteps). The execution can also easily and often jump from one thread to another.
> This arrangement is especially hard for developers that use features dependent on the threading model being more “stable,” such as ThreadLocal. As it lets you associate data with a thread, it becomes tricky to use in a reactive context. As a result, libraries that rely on ThreadLocal at least introduce new challenges when used with Reactor. At worst, they work badly or even fail. Using the MDC of Logback to store and log correlation IDs is a prime example of such a situation.


Since the GRpc Context is handled with the thread-local and the reactor and the GRpc doesn't know each other, there is no automatic propagation mechanism between the Grpc Context and Reactor Context.
