### ISSUE TITLE
Failed to create a channel using ManagedChannelBuilder

### ISSUE THREAD

**Issue by mlsalcedo** [yidongnan/grpc-spring-boot-starter#243]
I'm trying to create a channel based on metadata registered with the service in consul, we are creating the client using the code below:
```java
List<ServiceInstance> services = discoveryClient.getInstances(serviceId).stream()
                .filter(serviceInstance -> serviceInstance.getMetadata().containsKey(id) &&
                serviceInstance.getMetadata().get(id).equals(value)).collect(Collectors.toList());

        if (services != null && !services.isEmpty()) {
            ServiceInstance serviceInstance = services.get(0);
            int port = Integer.parseInt(serviceInstance.getMetadata().get("gRPC.port"));
            ManagedChannelBuilder<?> channelBuilder = ManagedChannelBuilder.forAddress(serviceInstance.getHost(), port);

            if (!isSecured) {
                channelBuilder =  channelBuilder.usePlaintext();
            }
            return StoremanGrpc.newStub(channelBuilder.build());
        }
```
and we always getting the following exception:
```java
ava.lang.NullPointerException: targetAuthority
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	at net.devh.boot.grpc.client.nameresolver.StaticNameResolverProvider.of(StaticNameResolverProvider.java:76) ~[grpc-client-spring-boot-autoconfigure-2.4.0.RELEASE.jar:2.4.0.RELEASE]
	at net.devh.boot.grpc.client.nameresolver.StaticNameResolverProvider.newNameResolver(StaticNameResolverProvider.java:63) ~[grpc-client-spring-boot-autoconfigure-2.4.0.RELEASE.jar:2.4.0.RELEASE]
	at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:233) ~[grpc-api-1.21.0.jar:1.21.0]
	at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154) ~[grpc-api-1.21.0.jar:1.21.0]
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:689) ~[grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:571) ~[grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:514) ~[grpc-core-1.21.0.jar:1.21.0]
	at com.hitachi.hcp.s3.utils.StoremanDiscoveryUtils.getInstanceByMetadata(StoremanDiscoveryUtils.java:40) ~[classes/:na]
	at com.hitachi.hcp.s3.service.GRPCClient.storemanReadObject(GRPCClient.java:246) ~[classes/:na]
	at com.hitachi.hcp.s3.service.S3ServiceImpl.lambda$getObject$0(S3ServiceImpl.java:99) ~[classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:110) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:97) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:323) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by ST-DDT** [comment]
Have you tried prefixing the address with `static://` ?

````java
ManagedChannelBuilder.forTarget("static://" + serviceInstance.getHost() + ":" + port);
````

--------------------

As an alternative you could use the inbuild injection feature?

````java
@Component
public class SomeService {

    @GrpcClient("storeman") // instead of @Autowired
    private StoremanStub storemanStub;

    public void doStuff() {
        storemanStub.magic(request);
    }

}
````

then you can easily configure it using just properties:

````properties
grpc.client.storeman.address=discovery:///serviceId
````

This approach has the added benefit, that 
* it can connect to more than one service instance and thus allows load balancing 
* as well as service re-resolution if there is a new service instance available

**Comment by mlsalcedo** [comment]
Thanks, I got it working using forTarget, the issue I'm facing now it's creating a continuous span and spring-sleuth is forcing me to use the other library in order to get it. I trying injecting GrpcTracing, but it does not help.
```
Spring Cloud Sleuth provides a SpringAwareManagedChannelBuilder that can be
 customized through the Spring application context and injected by gRPC clients. 
This builder must be used when creating ManagedChannel instances.
```

**Comment by ST-DDT** [comment]
I guess you refer to these classes:

https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/grpc

> the issue I'm facing now it's creating a continuous span and spring-sleuth is forcing me to use the other library in order to get it. 

How is it forcing you?

AFAICT all features that are present in that package are also available in this library:

[GrpcClientTraceAutoConfiguration](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientTraceAutoConfiguration.java)
[GrpcCommonTraceAutoConfiguration](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonTraceAutoConfiguration.java)

> SpringAwareManagedChannelBuilder: This builder must be used when creating ManagedChannel instances.

This is not true.

**Comment by mlsalcedo** [comment]
I did autowired GrpcTracing, i'm doing the following:

```java
int port = Integer.parseInt(serviceInstance.getMetadata().get("gRPC.port"));
GrpcChannelProperties properties = grpcChannelsProperties.getChannel(serviceId);
ManagedChannelBuilder<?> channelBuilder = ManagedChannelBuilder.forTarget(
        "static://" + serviceInstance.getHost() + ":" + port
);

channelBuilder.intercept(new OrderedClientInterceptor(
        grpcTracing.newClientInterceptor(),
        InterceptorOrder.ORDER_TRACING_METRICS + 1));
```
But I'm still getting 2 different spans, they are not connected.

**Comment by ST-DDT** [comment]
With two different spans you refer to one span per grpc call, don't you?

Is it possible that you need to create a span for that yourself? How would you achieve the same result with for example spring-rest (or similar libraries)?
https://cloud.spring.io/spring-cloud-sleuth/2.0.x/multi/multi__span_lifecycle.html

Could you post that part of the code as well? (I'm not familiar with at library)

**Comment by mlsalcedo** [comment]
Everything is working now, I just joined like you already stated in your last comment:
```java
Span readingSpan = tracer.currentSpan();
final StreamingResponseBody responseBody = outputStream -> {
    try (Tracer.SpanInScope ws = tracer.withSpanInScope(readingSpan)) {
```
