### ISSUE TITLE
How to change Max Header size?

### ISSUE THREAD

**Issue by marsradiant** [yidongnan/grpc-spring-boot-starter#256]
I'm getting error for Netty header size, is there any config to change the max header size?

``` WARN  i.g.n.NettyServerHandler : Stream Error
io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (8192)
        at io.netty.handler.codec.http2.Http2Exception.headerListSizeError(Http2Exception.java:171) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:228) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.HpackEncoder.encodeHeadersEnforceMaxHeaderListSize(HpackEncoder.java:122) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.HpackEncoder.encodeHeaders(HpackEncoder.java:106) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.DefaultHttp2HeadersEncoder.encodeHeaders(DefaultHttp2HeadersEncoder.java:68) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeadersInternal(DefaultHttp2FrameWriter.java:499) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeaders(DefaultHttp2FrameWriter.java:266) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.Http2OutboundFrameLogger.writeHeaders(Http2OutboundFrameLogger.java:60) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53) ~[netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.grpc.netty.NettyServerHandler$WriteMonitoringFrameWriter.writeHeaders(NettyServerHandler.java:949) ~[grpc-netty-1.14.0.jar!/:1.14.0]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:205) [netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:146) [netty-codec-http2-4.1.27.Final.jar!/:4.1.27.Final]
        at io.grpc.netty.NettyServerHandler.sendResponseHeaders(NettyServerHandler.java:638) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.grpc.netty.NettyServerHandler.write(NettyServerHandler.java:575) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1061) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:295) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:186) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44) [grpc-netty-1.14.0.jar!/:1.14.0]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [netty-transport-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar!/:4.1.25.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.25.Final.jar!/:4.1.25.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

**Comment by ST-DDT** [comment]
Which version of grpc-spring-boot-starter are you using?
From the logs it looks like you are using a very old one. Maybe v1.x?
AFAICT the old version has no property to configure it, you could either try to create a customized variant of [NettyGrpcServerFactory](https://github.com/yidongnan/grpc-spring-boot-starter/blob/v1.4.2.RELEASE/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/springboot/autoconfigure/grpc/server/NettyGrpcServerFactory.java#L24) or update to a recent version and configure it via [property](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java#L159)

**Comment by marsradiant** [comment]
Using Version 2.1.0.RELEASE

**Comment by ST-DDT** [comment]
That version does not have integrated supported for setting custom options:
You will have to create a `@Bean` from your subclass of [NettyGrpcServerFactory](https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.1.0.RELEASE/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/springboot/autoconfigure/grpc/server/NettyGrpcServerFactory.java) and customize the [`configureLimits()`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.1.0.RELEASE/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/springboot/autoconfigure/grpc/server/NettyGrpcServerFactory.java#L177) method.

From `v2.2.0` onwards you can use a [`GrpcServerConfigurer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.2.0.RELEASE/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerConfigurer.java) to configure the server freely without touching the existing features.

Please upgrade to a more recent version of grpc-spring-boot-starter!
