### ISSUE TITLE
使用注解@GrpcClient的时候找不到有效地址

### ISSUE THREAD

**Issue by liuhonbin** [yidongnan/grpc-spring-boot-starter#261]
这是报错信息
````txt
o.grpc.StatusRuntimeException: UNAVAILABLE: Name resolver returned no usable address. addrs=[], attrs={}
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233) ~[grpc-stub-1.20.0.jar:1.20.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214) ~[grpc-stub-1.20.0.jar:1.20.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139) ~[grpc-stub-1.20.0.jar:1.20.0]
	at com.grpc.time.TimeGrpc$TimeBlockingStub.getTime(TimeGrpc.java:157) ~[classes/:na]
	at com.service.TimeGrpcServerImpl.getTime(TimeGrpcServerImpl.java:26) ~[classes/:na]
	at com.order.OrderController.getTime(OrderController.java:40) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.4.RELEASE.jar:5.1.4.RELEASE]
````
这是我的配置文件

````yaml
spring:
  cloud:
    consul:
      discovery:
        tags: version=1.0,author=lhb
        healthCheckInterval: 1s
        service-name: order-consul-service
        health-check-path: /actuator/health
        ip-address: 192.168.10.238
        prefer-ip-address: true
      host: 192.168.12.213
      port: 32779
grpc:
  client:
    time:
      address: discovery:/time
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
````

这是 time的信息

````json
[
    {
        "instanceId": "192.168.13.249-5001",
        "serviceId": "time",
        "host": "192.168.13.249",
        "port": 5001,
        "secure": false,
        "metadata": {},
        "uri": "http://192.168.13.249:5001",
        "scheme": null
    }
]
````

**Comment by ST-DDT** [comment]
Currently we don't use the default port to connect to the server:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L229
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java#L32

@yidongnan Should we default to the normal port if the grpc port property isn't present?

**Comment by LongylG** [comment]
I got same problem,I was  refer to the project:
https://github.com/yidongnan/spring-boot-grpc-example/blob/master/cloud-consul/
But,if grpc-server not regiser it look like normal.

**Comment by liuhonbin** [comment]
> 我遇到同样的问题，我参考了这个项目：
> [https](https://github.com/yidongnan/spring-boot-grpc-example/blob/master/cloud-consul/)：[//github.com/yidongnan/spring-boot-grpc-example/blob/master/cloud-consul/](https://github.com/yidongnan/spring-boot-grpc-example/blob/master/cloud-consul/)
> 但是，如果grpc-server没有注册，它看起来很正常。
My project is registered normally., Get it using @grpcclient，but I can't get the address

**Comment by liuhonbin** [comment]
> I got same problem,I was refer to the project:
> https://github.com/yidongnan/spring-boot-grpc-example/blob/master/cloud-consul/
> But,if grpc-server not regiser it look like normal.

My project is registered normally., Get it using @grpcclient，but I can't get the address

**Comment by LongylG** [comment]
I tried import below package:
  implementation 'net.devh:grpc-server-spring-boot-starter:2.4.0.RELEASE'
It can success get the address from consul,but a error was occur:
`I tried import below package:
  implementation 'net.devh:grpc-server-spring-boot-starter:2.4.0.RELEASE'
It can success get the address from consul,but a error was occur:
`

**Comment by liuhonbin** [comment]
> I tried import below package:
> implementation 'net.devh:grpc-server-spring-boot-starter:2.4.0.RELEASE'
> It can success get the address from consul,but a error was occur:

By default, the grpc client assumes that the server uses TLS and will try to use a secure connection. During development and for tests is it unlikely that the required certificates are available thus you have to switch to PLAINTEXT connection mode.
`grpc.client.(gRPC server name).negotiationType=PLAINTEXT`

**Comment by LongylG** [comment]
Yes,I forget to update server name.Now,my project work very well!

**Comment by liuhonbin** [comment]
> Yes,I forget to update server name.Now,my project work very well!

Your problem solved?

**Comment by LongylG** [comment]
@liuhonbin  Yes,i Guess.Haven't any problem occure until now.
