### ISSUE TITLE
Grpc server throwing Http2Exception

### ISSUE THREAD

**Issue by ming2020** [yidongnan/grpc-spring-boot-starter#288]
**The context**

The grpc server is not working, but grpc_health_probe status is SERVING.

**The bug**

When the server runs for a period of time, it throwing exception at grpc client request

**Stacktrace and logs**

```
2019-09-24 19:41:38.046  INFO 1 --- [-worker-ELG-3-1] i.g.n.s.i.g.n.N.connections              : Transport failed

io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET / 
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.20.0.jar!/:1.20.0]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

**Steps to Reproduce**

**The application's environment**

* Spring (boot): 2.1.5.RELEASE
* grpc-java:  1.20.0
* grpc-spring-boot-starter: 2.4.0.RELEASE
* java: version + architecture (64bit?) 12 64bit
* Other relevant libraries...

**Additional context**

* Did it ever work before?
Yes, in most cases, it's healthy.
* Do you have a demo?

**Comment by ST-DDT** [comment]
AFAICT you are receiving an HTTP 1 request, which won't be used by grpc-clients.
gRPC clients and server only run with HTTP 2
I assume this is either a stray application or a bot that send a http/web-request to the server by mistake.

**Comment by ST-DDT** [comment]
If you have more questions feel free to ask.

**Comment by naivefun** [comment]
@ming2020 I am seeing the same behaviour, how did you solve the problem?

**Comment by wsdl-king** [comment]
you may need to  use " envoy " to proxy this project.
