### ISSUE TITLE
After upgrading from 2.5.1 to 2.6.0 can't resolve DNS for gRPC

### ISSUE THREAD

**Issue by mattdkerr** [yidongnan/grpc-spring-boot-starter#300]
**The context**

A service is written that already connects to an Orbit server endpoint when beans are activated for the gRPC service controller (via gRPC Spring Boot library's annotation).

**The bug**

**Expected**: Connects correctly on non-Spring gRPC connections (the Orbit library makes the connection) same as in the previous version.

**Actual**: non-Spring gRPC connections on start-up are unable to resolve the hostname even though the host OS is able to.
Rolling back to 2.5.1 resolves the issue.

**Stacktrace and logs**

```> Task :rlzservice:composeUp
orbit-server uses an image, skipping
Building rService
SERVICES_HOST environment variable detected - will be used as hostname of service orbit-server (docker)'
SERVICES_HOST environment variable detected - will be used as hostname of service rService (docker)'
Probing TCP socket on docker:50056 of service 'orbit-server_1'
Waiting for TCP socket on docker:50056 of service 'orbit-server_1' (Connection refused (Connection refused))
Attaching to c3855c6c08d87648c11400d7125d592d_rlzservice__rService_1, c3855c6c08d87648c11400d7125d592d_rlzservice__orbit-server_1
rService_1         | Java Arguments -Xms256m -Xmx512m
rService_1         | Spring Environment: 
rService_1         | Spring Boot App Path: /app/rlzservice.jar
rService_1         | Using BOOTSTRAP_DISABLED true
rService_1         | Using BOOTSTRAP_SCRIPTS_DIR 
rService_1         | Using SUPERVISOR_DISABLED true
rService_1         | Using java version: '11'
rService_1         | 21:40:28.285 [main] DEBUG com.ea.pt.rService.rlzservice.rServiceEngineApp - Running rServiceEngine Application with args: []
orbit-server_1  | Listening for transport dt_socket at address: 5005
orbit-server_1  | [main] INFO orbit.application.impl.SettingsLoader - Searching for Orbit Settings...
orbit-server_1  | [main] INFO orbit.application.impl.SettingsLoader - No settings found. Using defaults.
Waiting for TCP socket on docker:50056 of service 'orbit-server_1' (Connection refused (Connection refused))
Waiting for TCP socket on docker:50056 of service 'orbit-server_1' (Connection refused (Connection refused))

rService_1         | 2019-11-22 21:40:30:712 [main] INFO  c.e.p.r.r.rServiceEngineApp$Companion - No active profile set, falling back to default profiles: default
Waiting for TCP socket on docker:50056 of service 'orbit-server_1' (Connection refused (Connection refused))
orbit-server_1  | [orbit-cpu-1] INFO orbit.server.OrbitServer - Starting Orbit server...
orbit-server_1  | [orbit-cpu-1] INFO orbit.server.pipeline.Pipeline - Started a rail worker with 32 rails and a 10000 entry buffer.
orbit-server_1  | [orbit-cpu-1] INFO orbit.server.service.GrpcEndpoint - Starting gRPC Endpoint on LocalServerInfo(port=50056, url=localhost:50056).port...
Waiting for TCP socket on docker:50056 of service 'orbit-server_1' (Connection refused (Connection refused))
orbit-server_1  | [orbit-cpu-1] INFO orbit.server.service.GrpcEndpoint - gRPC Endpoint started on LocalServerInfo(port=50056, url=localhost:50056).port.
orbit-server_1  | [orbit-cpu-1] INFO orbit.server.OrbitServer - Orbit server started successfully in 668ms.
TCP socket on docker:50056 of service 'orbit-server_1' is ready
Probing TCP socket on docker:10000 of service 'rService_1'
Waiting for TCP socket on docker:10000 of service 'rService_1' (Connection refused (Connection refused))
rService_1         | 2019-11-22 21:40:33:649 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
rService_1         | 2019-11-22 21:40:33:649 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.27]
rService_1         | 2019-11-22 21:40:33:752 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
Waiting for TCP socket on docker:10000 of service 'rService_1' (Connection refused (Connection refused))
rService_1         | 2019-11-22 21:40:34:911 [main] INFO  n.d.b.g.c.n.NameResolverRegistration - DiscoveryClientResolverFactory [scheme=discovery, discoveryClient=org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient@499683c4] is available -> Added to the NameResolverRegistry
rService_1         | 2019-11-22 21:40:34:914 [main] INFO  n.d.b.g.c.n.NameResolverRegistration - net.devh.boot.grpc.server.nameresolver.SelfNameResolverFactory@7dff6d05 is available -> Added to the NameResolverRegistry
rService_1         | 2019-11-22 21:40:35:257 [orbit-client-1] INFO  orbit.client.OrbitClient - Starting Orbit client...
rService_1         | 2019-11-22 21:40:35:267 [orbit-client-1] INFO  o.c.addressable.CapabilitiesScanner - Scanning for node capabilities...
rService_1         | 2019-11-22 21:40:38:379 [orbit-client-1] INFO  o.c.addressable.CapabilitiesScanner - Node capabilities scan complete in 3110ms. 1 implemented addressable(s) found. 1 addressable interface(s) found. 1 addressable class(es) found. 
rService_1         | 2019-11-22 21:40:38:780 [orbit-client-1] INFO  orbit.client.mesh.NodeLeaser - Joining cluster at 'orbit://orbit-server:50056/pt'...
rService_1         | 2019-11-22 21:40:38:887 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:38:890 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
Waiting for TCP socket on docker:10000 of service 'rService_1' (Connection refused (Connection refused))
rService_1         | 2019-11-22 21:40:40:084 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:40:085 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:40:41:798 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:41:798 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:40:44:671 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:44:671 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:40:49:199 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:49:199 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:40:54:941 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:40:54:941 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:41:05:080 [grpc-default-executor-0] ERROR n.d.b.g.c.n.DiscoveryClientNameResolver - No servers found for orbit-server:50056
rService_1         | 2019-11-22 21:41:05:081 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<1>: (orbit-server:50056)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for orbit-server:50056, cause=null}
rService_1         | 2019-11-22 21:41:08:801 [orbit-client-2] ERROR orbit.client.OrbitClient - Unhandled exception in Orbit Client.
rService_1         | io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29885661172ns. [closed=[], open=[[buffered_nanos=29887809481, waiting_for_connection]]]
rService_1         | 	at io.grpc.Status.asRuntimeException(Status.java:533)
rService_1         | 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
rService_1         | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
rService_1         | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
rService_1         | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
rService_1         | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
rService_1         | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
rService_1         | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
rService_1         | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
rService_1         | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
rService_1         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
rService_1         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
rService_1         | 	at java.base/java.lang.Thread.run(Thread.java:834)
rService_1         | 2019-11-22 21:41:08:807 [main] ERROR o.s.b.w.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/info/InfoEndpointAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.info.InfoEndpoint]: Factory method 'infoEndpoint' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grpcInfoContributor' defined in class path resource [net/devh/boot/grpc/server/autoconfigure/GrpcServerMetricAutoConfiguration.class]: Unsatisfied dependency expressed through method 'grpcInfoContributor' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rServiceServiceGrpc' defined in URL [jar:file:/app/rlzservice.jar!/BOOT-INF/classes!/com/ea/pt/rService/rlzservice/api/rServiceServiceGrpc.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rServiceEngineService' defined in URL [jar:file:/app/rlzservice.jar!/BOOT-INF/classes!/com/ea/pt/rService/rlzservice/rules/rServiceEngineService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'getActorFactory' defined in class path resource [com/ea/pt/rService/rlzservice/config/OrbitConfig.class]: Unsatisfied dependency expressed through method 'getActorFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getStage' defined in class path resource [com/ea/pt/rService/rlzservice/config/OrbitConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [orbit.client.OrbitClient]: Factory method 'getStage' threw exception; nested exception is java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 29885661172ns. [closed=[], open=[[buffered_nanos=29887809481, waiting_for_connection]]]
rService_1         | 2019-11-22 21:41:08:857 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]```

**Steps to Reproduce**

Steps to reproduce the behavior:
1. Update code base from 2.5.1 to 2.6.0 of the library.
2. Run Spring Boot app.
3. Observe that gRPC connections that aren't from gRPC Spring Boot library functionality no longer have working name resolution, and logging of handling is coming from the library instead of from the base grpc-java code.

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.0-RELEASE
* grpc-java: 0.8.10
* grpc-spring-boot-starter: 2.6.0.RELEASE
* java: version + architecture (64bit?) 11.0.5 LTS - Zulu - 64 bit
* protoc 3.10.0
* kotlin version 1.3.60

**Additional context**

* Did it ever work before? **Yes**
* Do you have a demo? Not at this time

**Comment by ST-DDT** [comment]
The are two reasons for this change of behavior:
1) The discovery client based name resolver now has a higher priority than the dns based one (if it is configured). Thus it will now consistently attempt to use it instead of pseudo randomly.
2) The the name resolvers are now registered in grpc's registry (https://github.com/yidongnan/grpc-spring-boot-starter/pull/280 https://github.com/yidongnan/grpc-spring-boot-starter/issues/174 https://github.com/grpc/grpc-java/issues/6153 and related ones)

There are 4 possible solutions:
* [Configure spring](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java#L118) to not use grpc default registry (manually configure all supported resolvers) This option might be removed in a future version of grpc-java.
* Configure grpc-java's registry to have a higher priority for dns based name resolution
* Add a scheme to your client address configuration (**recommended**) (`grpc.client.xyz.address=dns:///orbit-server:12345`) works for plain grpc-java as well
* Configure a default scheme in the [config](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelsProperties.java#L95) (`grpc.client.defaultScheme=dns`) works only for grpc-spring-boot-starter

Is the documentation regarding the name resolvers helpful?
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration#choosing-the-target

**Comment by ST-DDT** [comment]
I created a [PR at grpc-java](https://github.com/grpc/grpc-java/pull/6499) that details the usage expectations of the `MangagedChannelBuilder#forTarget(String)` method. Once that is merged I will create PRs for the libraries that fail to specify the `dns` scheme themselves.

**Comment by ST-DDT** [comment]
I added a section to the docs for this:
https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting#client-fails-to-resolve-domain-name
IMO this is a configuration issue, but grpc's documentation contradicts itself there, so I close this issue for now and wait for a reaction from upstream. If you have additional questions or suggestions regarding the documentation, feel free to leave a comment.

**Comment by mattdkerr** [comment]
Thank you so much for the detail. I will give your suggestions a try.

**Comment by mattdkerr** [comment]
I spoke with the primary maintainer of Orbit and he said he was going to resolve this by splitting the namespace and gRPC endpoint, so that users can use whatever scheme they want.
