### ISSUE TITLE
incompatible with grpc 1.30.0

### ISSUE THREAD

**Issue by naivefun** [yidongnan/grpc-spring-boot-starter#370]
in grpc 1.30.x there is error:

`Caused by: java.lang.ClassNotFoundException: io.grpc.InternalNotifyOnServerBuild`

This class is gone in grpc-api since 1.30.x. 1.29.0 is fine.

**Comment by ST-DDT** [comment]
Thanks for bringing this error to our attention.
Can you please paste the full stacktrace?

AFAIK we don't use that class directly, so I'm not sure which component causes the error.
Maybe a dependency conflict?

**Comment by naivefun** [comment]
@ST-DDT 
here it is

```
2020-06-14 15:40:10.410  INFO 47447 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-06-14 15:40:10.415 ERROR 47447 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.NoClassDefFoundError: io.grpc.InternalNotifyOnServerBuild
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at com.glodon.gdc.dataSetService.DatasetServiceApplication.main(DatasetServiceApplication.java:10) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.3.0.RELEASE.jar:2.3.0.RELEASE]
Caused by: java.lang.NoClassDefFoundError: io.grpc.InternalNotifyOnServerBuild
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:476) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:437) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1110) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:898) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:806) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:764) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078) ~[na:na]
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configureServices(AbstractGrpcServerFactory.java:110) ~[grpc-server-spring-boot-autoconfigure-2.8.0.RELEASE.jar:2.8.0.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configure(AbstractGrpcServerFactory.java:90) ~[grpc-server-spring-boot-autoconfigure-2.8.0.RELEASE.jar:2.8.0.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.createServer(AbstractGrpcServerFactory.java:72) ~[grpc-server-spring-boot-autoconfigure-2.8.0.RELEASE.jar:2.8.0.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:89) ~[grpc-server-spring-boot-autoconfigure-2.8.0.RELEASE.jar:2.8.0.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:49) ~[grpc-server-spring-boot-autoconfigure-2.8.0.RELEASE.jar:2.8.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.grpc.InternalNotifyOnServerBuild
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078) ~[na:na]
	... 34 common frames omitted
```

**Comment by ST-DDT** [comment]
Please check whether all of your grpc-java dependencies use the same version. (You can use the grpc-bom to fix any issues there)

**Comment by naivefun** [comment]
@ST-DDT  You're right. It's grpc-services' version is locked at 1.28 from the starter config. Excluding it resolves the issue.
