### ISSUE TITLE
Unexpected error occurred on client after upgrading to grpc 1.2.0

### ISSUE THREAD

**Issue by iamtiancaif** [yidongnan/grpc-spring-boot-starter#43]
My test demo is also from saturnism.

url:   https://github.com/saturnism/grpc-java-demos/tree/master/springboot

grpc-spring-boot-starter itself is ok. But when I start an eureka and grpc server, then issue a request from client, some error occurr.

This is the error stack:

> 2017-05-14 18:31:19 [pool-8-thread-1] ERROR [TaskUtils.java:95] - Unexpected error occurred in scheduled task.
io.grpc.StatusRuntimeException: UNAVAILABLE: Transport closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at com.example.echo.EchoServiceGrpc$EchoServiceBlockingStub.echo(EchoServiceGrpc.java:135)
	at com.example.grpc.springboot.Cmd.requestRegular(Cmd.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yidongnan** [comment]
You can use https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples  as a demo

**Comment by iamtiancaif** [comment]
Thanks a lot ~!

BTW, do you have any solution to do stress test for this integration of grpc & eureka ? About grpc QPS and eureka fail over.

I try to startup hundreds of grpc server and client, then kill and restart servers randomly. It's not easy to monitor and generate statistics figure.

**Comment by iamtiancaif** [comment]
And what about upgrade spring-boot to 1.5.3-RELEASE ??

**Comment by yidongnan** [comment]
@iamtiancaif  If you want to perform a stress test, you can refer --->  https://github.com/grpc/grpc-java/tree/master/benchmarks  
Health check is currently in the plan. If you have any good idea, welcome to submit PR
spring boot version upgrade to 1.5.2.RELEASE in 1.2.0 branch

**Comment by iamtiancaif** [comment]
Thanks. Health check is a good point. I'll keep track of your project.
