### ISSUE TITLE
maxInboundSize at client side not working

### ISSUE THREAD

**Issue by banandh** [yidongnan/grpc-spring-boot-starter#455]
Hi,

Using net.devh spring boot starter version 2.9.0 RELEASE in both client and service side code.

Recently encountered "Resource exhausted" error. As per the document added below entry in both server and client application property file.(i have used @GrpcClient and @GrpcService)

grpc.server.maxInboundMessageSize=50MB.

after modifying this value in property , i still see 4MB in the error log. its not taking the value whatever we are setting through property file. Please advise

**Comment by ST-DDT** [comment]
Could you please attach the stacktrace to this issue? This helps me to identify which component throws the error/needs to be configured.

**Comment by banandh** [comment]
this is the error we get in client code.

when I set this in code it works as expected. I need a way to resolve via properties.

2020-11-23-21:37:22:452 [grpc-default-executor-0] ERROR com.tuc.XXXXXXXdata.grpc.clients.XXXXXXXServiceClient.XXXXXXXFromRedis(55) transaction-ref=-2020-11-23T21-37-21.965 Error encountered during Get Data Service consumption
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 7519192
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at com.tuc.getdataservice.model.XXXXXXXGrpc$XXXXXXXBlockingStub.XXXXXXX(XXXXXXXGrpc.java:157)
	at com.tuc.XXXXXXXdata.grpc.clients.XXXXXXXServiceClient.XXXXXXXFromRedis(XXXXXXXServiceClient.java:46)
	at com.tuc.XXXXXXXdata.util.XXXXXXXUtil.XXXXXXXForSid(XXXXXXXUtil.java:41)
	at com.tuc.XXXXXXXdata.service.XXXXXXXDataService.getResponseForYY(XXXXXXXDataService.java:157)
	at com.tuc.XXXXXXXdata.service.XXXXXXXDataService.XXXXXXXData(XXXXXXXDataService.java:137)
	at com.tuc.XXXXXXXdata.grpc.controller.XXXXXXXDataGrpcController.XXXXXXXData(XXXXXXXDataGrpcController.java:57)
	at com.tuc.adviserdata.model.XXXXXXXDataForYYGrpc$MethodHandlers.invoke(XXXXXXXDataForYYGrpc.java:217)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ST-DDT** [comment]
> when I set this in code it works as expected

There seems to be missing something.

**Comment by pumano** [comment]
@banandh this occurs because it should be int type and should be with dashes: 
`max-inbound-message-size: 31457280`

**Comment by ST-DDT** [comment]
@banandh Is the problem still there?
Please consider updating and check that your properties are actually read. AFAICT the code is working as intended when the properties are set.

Please make sure that this method is called:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java#L164

Please note that the property exists for both the server and the client:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java#L229

`grpc.client.<name>.max-inbound-message-size=`
