### ISSUE TITLE
I got the following error message when I start the cloud-client.Could you please tell me what I did wrong.

### ISSUE THREAD

**Issue by NeptuneNeptune** [yidongnan/grpc-spring-boot-starter#466]
# The error message
```shell
2020-12-21 19:19:18.795  INFO 12476 --- [           main] n.d.b.g.c.a.GrpcClientAutoConfiguration  : Detected grpc-netty-shaded: Creating ShadedNettyChannelFactory + InProcessChannelFactory
2020-12-21 19:19:18.835  WARN 12476 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testService' defined in file [E:\projects-reborn\automated-testing\client\target\classes\com\flowpp\automated\client\controller\TestService.class]: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.defaultLoadBalancingPolicy(Ljava/lang/String;)Lio/grpc/internal/AbstractManagedChannelImplBuilder;
2020-12-21 19:19:18.836  INFO 12476 --- [           main] n.d.b.g.c.n.NameResolverRegistration     : DiscoveryClientResolverFactory [scheme=discovery, discoveryClient=org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient@2ed71727] was removed from the NameResolverRegistry
2020-12-21 19:19:18.846  INFO 12476 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-21 19:19:18.850 ERROR 12476 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    net.devh.boot.grpc.client.channelfactory.ShadedNettyChannelFactory.newChannelBuilder(ShadedNettyChannelFactory.java:73)

The following method did not exist:

    io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.defaultLoadBalancingPolicy(Ljava/lang/String;)Lio/grpc/internal/AbstractManagedChannelImplBuilder;

The method's class, io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder, is available from the following locations:

    jar:file:/E:/runtime-env/apache-maven-3.6.3/repository/io/grpc/grpc-netty-shaded/1.33.0/grpc-netty-shaded-1.33.0.jar!/io/grpc/netty/shaded/io/grpc/netty/NettyChannelBuilder.class

It was loaded from the following location:

    file:/E:/runtime-env/apache-maven-3.6.3/repository/io/grpc/grpc-netty-shaded/1.33.0/grpc-netty-shaded-1.33.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
```
# My config file
```yml
grpc:
  client:
    my-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  instance:
    preferIpAddress: true
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: https://localhost:xxxx/eureka/
```

Please help me,thank you.

**Comment by NeptuneNeptune** [comment]
I've solved the problem by change the version of grpc-netty and grpc-netty-shaded,but I got another problem.
```shell
io.grpc.StatusRuntimeException: UNAVAILABLE: Could not find server: server
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.33.0.jar:1.33.0]
	at com.flowpp.automated.common.grpc.RequestGrpc$RequestBlockingStub.report(RequestGrpc.java:238) ~[classes/:na]
	at com.flowpp.automated.client.controller.TestService.test(TestService.java:22) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_271]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_271]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_271]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
```
I‘ve try many times,but I still can't solve this problem.
My server config:
```yml
server:
  port: 3000

spring:
  application:
    name: server

grpc:
  server:
    port: 3333
    enable-keep-alive: true
```
My client config:
```yml
grpc:
  client:
    server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
```
Help please.  Orz

**Comment by ST-DDT** [comment]
You don't specify the server's adress.
If you wish to connect to your own server use the self address or an in-process server.
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#choosing-the-target

**Comment by ST-DDT** [comment]
Does this solve your issues?

**Comment by luanweijie** [comment]
any update?

**Comment by ST-DDT** [comment]
> any update?

Status: feedback required

**Comment by luanweijie** [comment]
Works perfectly with the following versions:
Dependencies
grpc-java v1.31.1
protobuf v3.12.4
spring-boot v2.3.3
spring-cloud Hoxton.SR7 
But does not support
spring-cloud Hoxton.SR9

**Comment by uweschaefer** [comment]
to me, it looks like, there is a dependency snag in 2.10.1. We got a complaint from one of our users hinting at:
![image](https://user-images.githubusercontent.com/546815/106725778-05538d80-660a-11eb-8686-ece9aa5e0a72.png)

Which grpc version is supposed to be used here? 1.33 or 1.31.1?
It looks like 1.31.1 is working nicely, where 1.33 breaks some client code.

**Comment by ST-DDT** [comment]
I'm not sure where you got the managed dependency from. Might be spring that manages an incompatible version.
https://github.com/grpc/grpc-java/releases/tag/v1.33.1

> Fix builders ABI backward compatibility broken in v1.33.0, see #7552

**Comment by uweschaefer** [comment]
yep. my bad. it was managed somewhere in another BOM.

**Comment by felipeespitalher** [comment]
Hey guys ...

I'm using all versions described at README.md and still facing this issue. How may I fix it ?

**Comment by uweschaefer** [comment]
if you use maven use the effective-pom to **make sure**, your using what you intended. I am sure there is something comparable for gradle, if that is your cup of tea.

**Comment by ST-DDT** [comment]
@felipeespitalher Please give me a stacktrace, your used dependencies (grpc+netty related) and your grpc related config.

**Comment by NeptuneNeptune** [comment]
> Hey guys ...
> 
> I'm using all versions described at README.md and still facing this issue. How may I fix it ?

I turned to use WebSocket months ago, so I can't help you, sorry.
