### ISSUE TITLE
grpc-spring-boot-starter Tracing 的 Interceptor 问题

### ISSUE THREAD

**Issue by qianxunclub** [yidongnan/grpc-spring-boot-starter#493]
需要实现 tracing 调用链路，但是我们没有使用 springcloud

在使用的时候默认貌似需要自动注入 sleuth 的 TraceAutoConfiguration 类，导致报错找不到类

springboot 版本：2.4.1
grpc-spring-boot-starter 版本：2.10.1.RELEASE

**Comment by ST-DDT** [comment]
[English translation](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://github.com/yidongnan/grpc-spring-boot-starter/issues/493)

----------------------

Could you please include the stacktrace?

**Comment by asarkar** [comment]
Can we not have people file tickets in non-English languages unless they also provide translations? It prevents these tickets from showing up in searches, and creates a precedence where others can file tickets using any of the 7000 languages known to humans.

**Comment by qianxunclub** [comment]
pom.xml
```
        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-grpc</artifactId>
            <version>5.13.3</version>
        </dependency> 
```

Bean

```
    @Bean
    public GlobalServerInterceptorConfigurer globalServerInterceptorConfigurer(GrpcTracing grpcTracing) {
        return registry -> registry.add(grpcTracing.newServerInterceptor());
    }

    @Bean
    public GlobalClientInterceptorConfigurer globalClientInterceptorConfigurer(GrpcTracing grpcTracing) {
        return registry -> registry.add(grpcTracing.newClientInterceptor());
    }
```

error:

```
2021-02-19 11:26:00.121 [main] ERROR o.s.b.SpringApplication - [reportFailure,856] - Application run failed
java.lang.IllegalArgumentException: Could not find class [org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334)
	at org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:446)
	at org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:369)
	at org.springframework.core.annotation.TypeMappedAnnotation.asMap(TypeMappedAnnotation.java:284)
	at org.springframework.core.annotation.AbstractMergedAnnotation.asAnnotationAttributes(AbstractMergedAnnotation.java:193)
	at org.springframework.core.type.AnnotatedTypeMetadata.getAnnotationAttributes(AnnotatedTypeMetadata.java:106)
	at org.springframework.context.annotation.AnnotationConfigUtils.attributesFor(AnnotationConfigUtils.java:285)
	at org.springframework.context.annotation.AnnotationBeanNameGenerator.determineBeanNameFromAnnotation(AnnotationBeanNameGenerator.java:102)
	at org.springframework.context.annotation.AnnotationBeanNameGenerator.generateBeanName(AnnotationBeanNameGenerator.java:81)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.registerBeanDefinitionForImportedConfigurationClass(ConfigurationClassBeanDefinitionReader.java:169)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:150)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:348)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:252)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:285)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:99)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
```

**Comment by ST-DDT** [comment]
Might be an incompatibility in the latest spring versions. I'll fix it if I have some free time.

**Comment by Jereminet** [comment]
Hi,

We are using SpringBoot (v2.4.4) with your grpc-spring-boot-starter (v2.11.0.RELEASE) and ran exactly into the same issue which is quite a serious blocker for our implementation.

We would really appreciate a fix in the next release.

Regards,
Jeremy

**Comment by ST-DDT** [comment]
Could you please test whether the issue is still present in the latest snapshots?

**Comment by Jereminet** [comment]
Sure, where can I find the snapshot versions ?

**Comment by ST-DDT** [comment]
https://oss.sonatype.org/content/groups/public/net/devh/grpc-spring-boot-starter/2.12.0-SNAPSHOT/

**Comment by Jereminet** [comment]
When I extract the jar I cannot see any source code files, only the META-INF directory with license and manifest :/
Am I missing something here ?

**Comment by ST-DDT** [comment]
Sorry for not being that precise. That dependency is the core dependency. The other modules use a different path:

E.g.: https://oss.sonatype.org/content/groups/public/net/devh/grpc-server-spring-boot-autoconfigure/2.12.0-SNAPSHOT/

PS: It might be useful to temporarily add `https://oss.sonatype.org/content/groups/public/` or a similar path to your maven repositories (This is what I assumed you would do).

**Comment by blackhogz** [comment]
Providing a signal here that I ran into this exact issue and updating the version to 2.12.0-SNAPSHOT fixed it. Thanks!

What is the release schedule? When can I expect this to be available as a release at a more standard/popular maven repo?

**Comment by ST-DDT** [comment]
The update is schedulled for this month.
But it depends a bit on how much time I have to finish the remaining tasks and @yidongnan to review the PRs.

**Comment by qbmiller** [comment]
we have met the same problem; 

> java.lang.IllegalArgumentException: Could not find class [org.springframework.cloud.sleuth.autoconfig.brave.BraveAutoConfiguration]

`  <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>2.4.5</version>
 <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>2.12.0.RELEASE</version>
        </dependency>

  <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-http</artifactId>
        </dependency>

        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-spring-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-rpc</artifactId>
        </dependency>

        <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-instrumentation-grpc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>

        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-sender-okhttp3</artifactId>
        </dependency>

 <dependencyManagement>
 <dependencies>
 <dependency>
                <groupId>io.zipkin.brave</groupId>
                <artifactId>brave-bom</artifactId>
                <version>5.12.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
     </dependencies>
    </dependencyManagement>
`

**Comment by ST-DDT** [comment]
Which version of spring cloud are you using?

**Comment by qbmiller** [comment]
> Which version of spring cloud are you using?

we don't use springcloud; 
just springboot + grpc ; 
but we reference zipkin alone for b3-trace

**Comment by ST-DDT** [comment]
Then try excluding this auto configuration and create the related bean yourself:

[GrpcCommonTraceAutoConfiguration](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonTraceAutoConfiguration.java#L35)

**Comment by qbmiller** [comment]
> Then try excluding this auto configuration and create the related bean yourself:
> 
> [GrpcCommonTraceAutoConfiguration](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonTraceAutoConfiguration.java#L35)

ok . 3Q

**Comment by ST-DDT** [comment]
Does that fix the issue for you?
If yes, I'll try to circumvent this issue in the next release.
