### ISSUE TITLE
Fix randomly failing tests

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#537]
The build pipeline in github seems to fail randomly on some tests.
Unfortunately, I'm unable to reproduce the error both at home or at work.
I literally ran the tests continuously for 4h hours (~150 runs/env) on both places and they didn't even fail once.

We should (temporarily) adjust the tests so that they provide more information where they failed and run the tests with extended logs enabled to help with narrowing down the issues.

**Comment by ST-DDT** [comment]
````txt
MetricCollectingInterceptorTest > testMetricsFailedCall() FAILED
    org.opentest4j.AssertionFailedError: execution timed out after 1000 ms
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:158)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:119)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:101)
        at org.junit.jupiter.api.AssertTimeout.assertTimeoutPreemptively(AssertTimeout.java:97)
        at org.junit.jupiter.api.Assertions.assertTimeoutPreemptively(Assertions.java:3323)
        at net.devh.boot.grpc.test.metric.MetricCollectingInterceptorTest.testMetricsFailedCall(MetricCollectingInterceptorTest.java:497)
````

**Comment by ST-DDT** [comment]
````txt
GrpcReflectionServiceFalseAutoConfigurationTest > testReflectionService() PASSED

GrpcReflectionServiceTrueAutoConfigurationTest > testReflectionService() FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
    Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.IllegalStateException: Failed to start the grpc server
        Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:9090

GrpcHealthServiceFalseAutoConfigurationTest > testHealthService() PASSED

GrpcHealthServiceTrueAutoConfigurationTest > testHealthService() FAILED
````

**Comment by ST-DDT** [comment]
````txt
GrpcServerLifecycleTest > testNoGraceShutdown() PASSED

GrpcReflectionServiceFalseAutoConfigurationTest > testReflectionService() FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext
        Caused by: org.springframework.context.ApplicationContextException: Failed to start bean
            Caused by: java.lang.IllegalStateException: Failed to start the grpc server
                Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:9090
                    Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

GrpcReflectionServiceTrueAutoConfigurationTest > testReflectionService() PASSED

GrpcHealthServiceFalseAutoConfigurationTest > testHealthService() PASSED

GrpcHealthServiceTrueAutoConfigurationTest > testHealthService() PASSED

GrpcReflectionServiceDefaultAutoConfigurationTest > testReflectionService() PASSED

GrpcHealthServiceDefaultAutoConfigurationTest > testHealthService() PASSED
````
