### ISSUE TITLE
UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR

### ISSUE THREAD

**Issue by shivam2146** [yidongnan/grpc-spring-boot-starter#551]
**The context**
Inter-service communication using gRPC

**The bug**
gRPC client giving error `UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR` while calling the server.

**Stacktrace and logs**

`UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR`
`  at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
  at com.demo.gpc.DemoGrpc$DemoBlockingStub.hasAccess(DemoGrpc.java:209)
  at com.demo.service.GrpcClient.hasAccess(GrpcClient.java:27)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)`

**Steps to Reproduce**

1. Create a gRPC server with blocking stub
2. Create a client for this server
3. If the gRPC server stub method takes longer durations to execute we start seeing the above error in logs after every minute or so.

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-spring-boot-starter: 2.12.0.RELEASE
* java: amazoncorretto:11 (JDK) and 64bit
* grpc-netty-shaded:1.37.0

**Additional context**
Don't see these errors when the stub method is not doing much processing and just returning some dummy data.
The error rate is increased in following scenarios:
1. When we increase the rpm or concurrent calls to server
2. When the rpc method starts taking more time to process

**Comment by ST-DDT** [comment]
This question seems to be related to grpc-java itself only. It's better to ask these questions over at https://github.com/grpc/grpc-java as they know their internals better than we do.
Please link the issue here, to simplify future lookups of similar errors.
