### ISSUE TITLE
io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted

### ISSUE THREAD

**Issue by nitinmeharia** [yidongnan/grpc-spring-boot-starter#555]
**The bug**

On creating the new instance, we see the following error.
Onces the connections are established, we don't see it any longer

```
io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted
  at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
  at pb.lyft.code.MyCode$MyCode.myFunc(MyServiceGrpc.java:178)
  at com.xxx.xx.xx.code.MyServiceGrpc.myFunc2(MyServiceGrpc.java:99)
  at com.xx.xx.xx.xx.MyServiceGrpc.myFunc3(MyServiceGrpc.java:69)
  at sun.reflect.GeneratedMethodAccessor460.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:116)
  at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.executeWithArgs(MethodExecutionAction.java:93)
  at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:78)
  at com.netflix.hystrix.contrib.javanica.command.GenericCommand$1.execute(GenericCommand.java:48)
  at com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommand.process(AbstractHystrixCommand.java:145)
  at com.netflix.hystrix.contrib.javanica.command.GenericCommand.run(GenericCommand.java:45)
  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
  at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.Observable.unsafeSubscribe(Observable.java:10327)
  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
  at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
  at rx.Observable.unsafeSubscribe(Observable.java:10327)
  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
  at rx.Observable.unsafeSubscribe(Observable.java:10327)
  at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
  at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:69)
  at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)Caused by: java.lang.InterruptedException: nulls
  at io.grpc.stub.ClientCalls$ThreadlessExecutor.throwIfInterrupted(ClientCalls.java:749)
  at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:732)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149) ... 42 common frames omitteds

```

**Steps to Reproduce**

1. Every time we create an instance, we see these issues. And once the connections are establishes, it doesn't occur.

**The application's environment**

Which versions do you use?
* Spring (boot):2.0.3.RELEASE
* grpc-client-spring-boot-starter: 2.10.1.RELEASE
* java: openjdk-8

**Comment by ST-DDT** [comment]
I don't see any code related to this library in the stacktrace.
Have you checked where the thread gets interrupted?

> On creating the new instance, we see the following error.

Which instance are you referring to?
