### ISSUE TITLE
INTERNAL: grpc: failed to unmarshal the received message proto: cannot parse invalid wire-format data

### ISSUE THREAD

**Issue by xieyanfds** [yidongnan/grpc-spring-boot-starter#571]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?

I encountered a problem. At present, we have defined a grpc normal stream interface, and the following error occurs in high scenarios

grpc: failed to unmarshal the received message proto: cannot parse invalid wire-format data

**Stacktraces and logs**

````txt
[33m2021-08-03 12:20:33.206.[0;39m [grpc-default-executor-16] ERROR com.xxx.grpc.GrpcBatchHandler - GrpcBatchHa
ndler.onError:INTERNAL: grpc: failed to unmarshal the received message proto: cannot parse invalid wire-format data
io.grpc.StatusRuntimeException: INTERNAL: grpc: failed to unmarshal the received message proto: cannot parse invalid wire-form
at data
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:4
0)
	at net.devh.boot.grpc.client.metric.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java
:59)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**The application's environment**

Which versions do you use?

````xml
<dependency>
	<groupId>net.devh</groupId>
	<artifactId>grpc-client-spring-boot-starter</artifactId>
	<version>2.11.0.RELEASE</version>
	<exclusions>
		<exclusion>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-netty-shaded</artifactId>
		</exclusion>
	</exclusions>
</dependency>

<!--grpc-->
<dependency>
	<groupId>io.grpc</groupId>
	<artifactId>grpc-netty-shaded</artifactId>
	<version>1.36.0</version>
</dependency>
<dependency>
	<groupId>io.grpc</groupId>
	<artifactId>grpc-protobuf</artifactId>
	<version>1.36.0</version>
</dependency>
<dependency>
	<groupId>io.grpc</groupId>
	<artifactId>grpc-stub</artifactId>
	<version>1.36.0</version>
</dependency>
````

* Spring (boot):  2.3.3.RELEASE
* java: version + architecture  java 1.8 64bit

my config is 

````yaml
grpc:
  client:
    grpc-server-test:
      address: static://10.1.10.14:38087
      enableKeepAlive: false
      keepAliveTime: 60
      keepAliveTimeOut: 20
      keepAliveWithoutCalls: false
      negotiationType: plaintext
      max-inbound-message-size: 33554432
      fullStreamDecompression: true
````

**Additional information**

**Comment by ST-DDT** [comment]
> and the following error occurs in high scenarios

What are you referring to with "high scenarios"?

Unfortunately the exception is non-descriptive so there is hardly anything we can do to help you.

IMO the most likely cause is that there are differences in the generated proto service definitions between server and client. Maybe in a rarely used/optional field/value, that causes these errors to be hard to predict.
If the error is reproducible, then maybe you can use wireshark or a similar tool to sniff the actual payload and try to debug, why it is invalid.

Other than that I can only recommend you to open an issue over at grpc-java and ping me/link this issue. Maybe they know a way to debug the error in more detail.

Which grpc+protobuf version does the server use? Have you tried using the same/latest versions?

**Comment by xieyanfds** [comment]
Thanks answer，
“high scenarios“ is google translate, that's meaning is not correct，What I want to say is in high concurrency scenarios，
I use multiple threads to operate StreamObserver send request，but the server cannot receive the message probabilistically.

Last night I tried to send a message using a single thread，Works perfectly，so I guess whether it is necessary to configure a multi-threaded stub，I'm trying to find a solution.

the server version is consistent，there is no problem with low concurrency，only occurs when there is high concurrency.

**Comment by ST-DDT** [comment]
Thanks for the additional information.

This behaviour seems like a bug in the underlying grpc-java library.

Please try again with the latest grpc-java versions or report this behavior to grpc-java directly.
