### ISSUE TITLE
How to use grpcRequest scoped beans in child threads

### ISSUE THREAD

**Issue by sunchaser-lilu** [yidongnan/grpc-spring-boot-starter#631]
**The context**

What do you wish to achieve?

Using grpcRequest scoped beans in child threads

**The question**

What's the problem? What's not working? What's missing and why do you need it?

Below is an example of usage：

```
import lombok.Data;
import net.devh.boot.grpc.server.scope.GrpcRequestScope;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;

@Component
@Scope(value = GrpcRequestScope.GRPC_REQUEST_SCOPE_NAME, proxyMode = ScopedProxyMode.TARGET_CLASS)
@Data
public class GrpcRequestScopeBean {
    private String val;
}
...

@GrpcService
@Slf4j
public class GrpcServerService extends GreeterGrpc.GreeterImplBase {

    @Autowired
    private GrpcRequestScopeBean grpcRequestScopeBean;

    private static final ExecutorService executors = Executors.newFixedThreadPool(2);

    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver){
        
        CountDownLatch countDownLatch = new CountDownLatch(2);
        executors.execute(() -> {
            String val = grpcRequestScopeBean.getVal();
            countDownLatch.countDown();
        });

        executors.execute(() -> {
            String val = grpcRequestScopeBean.getVal();
            countDownLatch.countDown();
        });

        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        HelloReply reply = HelloReply.newBuilder().setMessage(("Hello "+req.getName())).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
        log.info("Message from gRPC-Client:" + req.getName());
    }
}
```

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

```
Exception in thread "pool-4-thread-1" org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'scopedTarget.grpcRequestScopeBean': Scope 'grpcRequest' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Trying to access grpcRequest-Scope, but it was not started for this thread.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:383)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:676)
...

Caused by: java.lang.IllegalStateException: Trying to access grpcRequest-Scope, but it was not started for this thread.
	at net.devh.boot.grpc.server.scope.GrpcRequestScope.getCurrentScopeContainer(GrpcRequestScope.java:120)
	at net.devh.boot.grpc.server.scope.GrpcRequestScope.get(GrpcRequestScope.java:80)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371)
	... 8 more

```

**The application's environment**

Which versions do you use?
* Spring (boot): 2.5.5
* grpc-java: 1.42.2
* grpc-spring-boot-starter: 2.13.1.RELEASE
* java: version + architecture (64bit?) : jdk11(64bit)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by sunchaser-lilu** [comment]
Thanks, I solved the problem using the following line of code

```
Executor executor = Context.currentContextExecutor(executors);
......
```
