### ISSUE TITLE
Getting error whenever I run my tests with SpringBootTest - java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by obaidsalikeen** [yidongnan/grpc-spring-boot-starter#686]
I am experiencing following error whenever I try to run my tests using the approach listed under `Spring-based Tests` section.

Is this a known issue? I also tried after changing the port to 9091 and it still fails

Error:
[ERROR] verifyAccountIdAndPartnerPassedToSubAPI  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.IllegalStateException: Failed to start the grpc server
Caused by: java.lang.IllegalStateException: Failed to start the grpc server
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:9090
Caused by: java.net.BindException: Address already in use

**Comment by obaidsalikeen** [comment]
I tried in process with following configurations:
grpc:
  client:
    inProcess:
      address: in-process:test
  server:
    in-process-name: test
    port: -1

but I still get this error:

Caused by: java.lang.IllegalStateException: Failed to start the grpc server
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:74)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 84 more
Caused by: java.io.IOException: name already registered: test
	at io.grpc.inprocess.InProcessServer.start(InProcessServer.java:76)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:113)
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:72)
	... 85 more

**Comment by obaidsalikeen** [comment]
Solution that worked for me was to use a random port option (ser the port to 0).

I tried using DirtiesContext but it slowed down the execution time, and I needed to update all the tests
