### ISSUE TITLE
Client Request gets UNKNOWN error with no further description

### ISSUE THREAD

**Issue by sgrannan** [yidongnan/grpc-spring-boot-starter#690]
Using just the **gprc-client-spring-boot-starter** I'm getting a strange error when attempting to execute a request to a GRPC server, and there is no supporting information. I've turned the log level up to TRACE. 

I'd like to figure out what library is causing the issue here. I've tried multiple versions of grpc-java but they all give me the same error when I try a simple Unary Blocking request to the grpc server. I can confirm the server works fine because I am able to make the same call successfully using **grpcurl**. 

I'm new to GRPC and I found that this Starter library gives me the auto config things I like about Spring Boot. Can anyone help me understand what these logs are trying to say?  Is there a setting or a library that is missing?

**Stack Trace**

> TRACE  [11:13:06.914] [grpc-default-executor-0] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Resolved address: [[[localhost/127.0.0.1:8050]/{}], [[localhost/0:0:0:0:0:0:0:1:8050]/{}]], config={} 
> TRACE  [11:13:06.914] [grpc-default-executor-0] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Address resolved: [[[localhost/127.0.0.1:8050]/{}], [[localhost/0:0:0:0:0:0:0:1:8050]/{}]] 
> TRACE  [11:13:06.970] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<3>: (localhost:8050)] Subchannel for [[[localhost/127.0.0.1:8050]/{}]] created 
> TRACE  [11:13:06.996] [grpc-default-executor-0] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Child Subchannel started 
> TRACE  [11:13:07.000] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<4>: (localhost:8050)] Subchannel for [[[localhost/0:0:0:0:0:0:0:1:8050]/{}]] created 
> TRACE  [11:13:07.000] [grpc-default-executor-0] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Child Subchannel started 
> TRACE  [11:13:07.010] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<3>: (localhost:8050)] CONNECTING as requested 
> DEBUG  [11:13:08.449] [grpc-default-executor-0] i.g.n.Utils -  Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true 
> DEBUG  [11:13:08.454] [grpc-default-executor-0] i.g.n.Utils -  Creating allocator, preferDirect=true 
> DEBUG  [11:13:08.455] [grpc-default-executor-0] i.g.n.Utils -  Forcing maxOrder=8 
> TRACE  [11:13:08.822] [grpc-nio-worker-ELG-1-2] i.g.ChannelLogger -  [NettyClientTransport<5>: (localhost/127.0.0.1:8050)] WaitUntilActive started 
> TRACE  [11:13:08.908] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<3>: (localhost:8050)] Started transport NettyClientTransport<5>: (localhost/127.0.0.1:8050) 
> TRACE  [11:13:08.908] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<4>: (localhost:8050)] CONNECTING as requested 
> DEBUG  [11:13:08.909] [grpc-default-executor-0] i.g.n.Utils -  Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true 
> TRACE  [11:13:08.911] [grpc-default-executor-0] i.g.ChannelLogger -  [Subchannel<4>: (localhost:8050)] Started transport NettyClientTransport<6>: (localhost/0:0:0:0:0:0:0:1:8050) 
> TRACE  [11:13:08.911] [grpc-nio-worker-ELG-1-3] i.g.ChannelLogger -  [NettyClientTransport<6>: (localhost/0:0:0:0:0:0:0:1:8050)] WaitUntilActive started 
> TRACE  [11:13:08.917] [grpc-default-executor-0] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Entering CONNECTING state with picker: EmptyPicker{status=Status{code=OK, description=null, cause=null}} 
> TRACE  [11:13:08.958] [grpc-nio-worker-ELG-1-3] i.g.ChannelLogger -  [NettyClientTransport<6>: (localhost/0:0:0:0:0:0:0:1:8050)] WaitUntilActive completed 
> TRACE  [11:13:08.958] [grpc-nio-worker-ELG-1-2] i.g.ChannelLogger -  [NettyClientTransport<5>: (localhost/127.0.0.1:8050)] WaitUntilActive completed 
> DEBUG  [11:13:09.017] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192} 
> DEBUG  [11:13:09.017] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192} 
> DEBUG  [11:13:09.097] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041 
> DEBUG  [11:13:09.097] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041 
> DEBUG  [11:13:09.192] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192} 
> DEBUG  [11:13:09.192] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192} 
> DEBUG  [11:13:09.197] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND SETTINGS: ack=true 
> DEBUG  [11:13:09.199] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] OUTBOUND SETTINGS: ack=true 
> TRACE  [11:13:09.203] [grpc-nio-worker-ELG-1-3] i.g.ChannelLogger -  [Subchannel<4>: (localhost:8050)] READY 
> TRACE  [11:13:09.204] [grpc-nio-worker-ELG-1-2] i.g.ChannelLogger -  [Subchannel<3>: (localhost:8050)] READY 
> DEBUG  [11:13:09.209] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041 
> DEBUG  [11:13:09.211] [grpc-nio-worker-ELG-1-2] i.g.n.NettyClientHandler -  [id: 0x6f7e2539, L:/127.0.0.1:54616 - R:localhost/127.0.0.1:8050] INBOUND SETTINGS: ack=true 
> TRACE  [11:13:09.388] [grpc-nio-worker-ELG-1-3] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Entering READY state with picker: ReadyPicker{list=[Subchannel<4>: (localhost:8050)]} 
> TRACE  [11:13:09.389] [grpc-nio-worker-ELG-1-3] i.g.ChannelLogger -  [Channel<1>: (localhost:8050)] Entering READY state with picker: ReadyPicker{list=[Subchannel<3>: (localhost:8050), Subchannel<4>: (localhost:8050)]} 
> DEBUG  [11:13:09.389] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041 
> DEBUG  [11:13:09.389] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] INBOUND SETTINGS: ack=true 
> DEBUG  [11:13:09.551] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:8050, :path: /polaris.credential.CredentialService/createCredential, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.37.0, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false 
> DEBUG  [11:13:09.633] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=43 bytes=00000000261a2464373237313134622d356437612d346135322d386666312d393832353339303166326236 
> DEBUG  [11:13:09.643] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] INBOUND PING: ack=false bytes=1234 
> DEBUG  [11:13:09.644] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND PING: ack=true bytes=1234 
> DEBUG  [11:13:09.673] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-status: 2] padding=0 endStream=true 
> DEBUG  [11:13:13.521] [grpc-nio-worker-ELG-1-3] i.g.n.NettyClientHandler -  [id: 0x801cadd8, L:/0:0:0:0:0:0:0:1:54615 - R:localhost/0:0:0:0:0:0:0:1:8050] OUTBOUND RST_STREAM: streamId=3 errorCode=8 
> ERROR  [11:13:13.528] [http-nio-9090-exec-1] c.p.m.c.s.CredentialService -  UNKNOWN 
> io.grpc.StatusRuntimeException: UNKNOWN
> 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
> 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
> 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)

**The application's environment**
I'm using a bit updated version of Spring Boot because the 2.14 RELEASE isn't out yet...
* Spring (boot): 2.6.4
* grpc-java: 1.46 (I've tried 1.37 too with same result)
* grpc-spring-boot-starter: 2.13
* java: version + architecture (64bit?) jdk 11 64bit

**Comment by sgrannan** [comment]
So the server, which is not my implementation, was not providing good enough error information back to the client.
