### ISSUE TITLE
如何使用安全认证模块（SSL设置搭建失败）

### ISSUE THREAD

**Issue by banyue0618** [yidongnan/grpc-spring-boot-starter#879]
**The context**

我想要实现安全认证功能，但是第一步基本的SSL设置都是失败了，启动项目报错，对于错误也是一头雾水。
我自己通过查看网上的博客使用openssl，生成CA，再通过CA生成客户端服务端证书，开启TLS后启动服务端失败。

**The question**
yml配置
`grpc:
  server:
    port: 0
    security:
      enabled: true
      certificate-chain: classpath:keys/server/server.cer
      private-key: classpath:keys/server/server.key
      private-key-password: 123456
      client-auth: require
      trust-cert-collection: classpath:keys/client/client.cer`

pom引用
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>micro-service-spring-cloud-grpc-proto</artifactId>
    <properties>
        <protobuf.version>3.19.1</protobuf.version>
        <protobuf-plugin.version>0.6.1</protobuf-plugin.version>
        <grpc.version>1.42.1</grpc.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.19.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-okhttp</artifactId>
        </dependency>

        
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>1.34.1</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.31.Final</version>
        </dependency>
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-server-spring-boot-starter</artifactId>
            <version>2.13.1.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.19.0</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.0</version>
            </extension>
        </extensions>

        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>${protobuf-plugin.version}</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>14<protoSourceRoot>src/main/proto</protoSourceRoot>
                    <outputDirectory>src/main/java</outputDirectory>
                    <clearOutputDirectory>false</clearOutputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

**Stacktraces and logs**
`
org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.IllegalArgumentException: Failed to create SSLContext (PK/Cert)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at com.banyue.MicroServiceDeptApplication.main(MicroServiceDeptApplication.java:23) [classes/:na]
Caused by: java.lang.IllegalArgumentException: Failed to create SSLContext (PK/Cert)
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerSslContextBuilder(ShadedNettyGrpcServerFactory.java:168) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.configureSecurity(ShadedNettyGrpcServerFactory.java:116) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.configureSecurity(ShadedNettyGrpcServerFactory.java:54) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configure(AbstractGrpcServerFactory.java:88) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.createServer(AbstractGrpcServerFactory.java:67) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:111) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:72) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	... 14 common frames omitted
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid private key.
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:376) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:121) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:136) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerSslContextBuilder(ShadedNettyGrpcServerFactory.java:156) ~[grpc-server-spring-boot-autoconfigure-2.13.1.RELEASE.jar:2.13.1.RELEASE]
	... 21 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.13 SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122) ~[na:1.8.0_351]
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160) ~[na:1.8.0_351]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:1073) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1133) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1123) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:374) ~[grpc-netty-shaded-1.34.1.jar:1.34.1]
	... 24 common frames omitted`

**The application's environment**

Which versions do you use?
* Spring (boot):2.3.6.RELEASE
* grpc-java:
* grpc-spring-boot-starter:2.13.1.RELEASE
* java:1.8.0_361
* Other relevant libraries...

**Additional information**
对于这个问题实在不解，也采用指引文档中的命令生成相关证书
`openssl req -x509 -nodes -subj "//CN=localhost" -newkey rsa:4096 -sha256 -keyout client.key -out client.cer -days 3650`
但是依然不行，提示：Empty issuer DN not allowed in X509Certificates。
还望大佬看看，非常感谢！

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/879?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

I'll have a look later.

**Comment by ST-DDT** [comment]
> java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.13 SecretKeyFactory not available

Looks like you have to update java or add the missing algorithms using bouncy castle or otherwise.

**Comment by banyue0618** [comment]
thank you for your reply,maybe I need to use a lower version of openssl to generate the certificate.

**Comment by banyue0618** [comment]
> 

thank you for your reply,maybe I need to use a lower version of openssl to generate the certificate.

**Comment by banyue0618** [comment]
> 

thank you for your reply,maybe I need to use a lower version of openssl to generate the certificate.
