### ISSUE TITLE
连接超时错误:使用eureka注册和发现client找到了grpc-server地址，但是一直报连接超时。

### ISSUE THREAD

**Issue by 2YSP** [yidongnan/grpc-spring-boot-starter#93]
client日志如下：
`2018-08-23 11:06:30.290 ERROR 6664 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.grpc.StatusRuntimeException: UNAVAILABLE] with root cause

java.lang.RuntimeException: UNAVAILABLE: NameResolver returned an empty list
	at net.devh.springboot.autoconfigure.grpc.client.DiscoveryClientNameResolver$1.run(DiscoveryClientNameResolver.java:130) ~[grpc-client-spring-boot-autoconfigure-2.0.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

2018-08-23 11:06:52.377  WARN 6664 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [io.grpc.internal.ManagedChannelImpl-1] Failed to resolve name. status=Status{code=UNAVAILABLE, description=null, cause=java.lang.RuntimeException: UNAVAILABLE: NameResolver returned an empty list
	at net.devh.springboot.autoconfigure.grpc.client.DiscoveryClientNameResolver$1.run(DiscoveryClientNameResolver.java:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
}
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
2018-08-23 11:06:52.377  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2018-08-23 11:06:52.417  INFO 6664 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
2018-08-23 11:06:56.630  INFO 6664 --- [ault-executor-0] n.d.s.a.g.c.DiscoveryClientNameResolver  : Ready to update grpc-server server info group list
2018-08-23 11:06:56.630  INFO 6664 --- [ault-executor-0] n.d.s.a.g.c.DiscoveryClientNameResolver  : Found gRPC server grpc-server 172.12.1.115:47274
2018-08-23 11:09:24.437 ERROR 6664 --- [nio-8081-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.grpc.StatusRuntimeException: UNAVAILABLE: io exception] with root cause

java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_31]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[na:1.8.0_31]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-transport-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
`

**Comment by yidongnan** [comment]
@2YSP 运行的example出现的？

**Comment by 2YSP** [comment]
后来发现是公司内网问题。。。

**Comment by 2YSP** [comment]
能不能出个整合SpringCloudConsul的例子啊

**Comment by yidongnan** [comment]
@2YSP https://github.com/yidongnan/spring-boot-grpc-example/tree/master/cloud-consul
